quarkus:
  banner:
    enabled: true
    path: xbox-banner.txt
  liquibase:
    migrate-at-start: true
    search-path:
      - "db/changelog"
    change-log: "local/changelog.xml"
  datasource:
    db-kind: postgresql
    devservices:
      enabled: true
      reuse: false
      image-name: "postgres:14.10-alpine"
      container-env:
        "POSTGRES_DB": "car-management"
        "POSTGRES_USER": "postgres"
        "PASSWORD": "postgres"
      port: 5433
      volumes:
        "db/init-db": "/docker-entrypoint-initdb.d"
      db-name: "car-management"
      username: "postgres"
      password: "postgres"
    jdbc:
      url: jdbc:postgresql://localhost:5433/car-management?currentSchema=car_management
      initial-size: 2
      min-size: 2
      max-size: 5
  hibernate-orm:
    packages: com.ctw.car
    validate-in-dev-mode: false
    database:
      generation: none
    log:
      sql: ${hibernate_orm_log_sql:true}